artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1ngwlRIbEf6BRg-Tw_C5mGGg1JXGe2KP6/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_transformation:
  root_dir: artifacts/data_transformation
  train_data_path: artifacts/data_transformation/train.npy
  test_data_path: artifacts/data_transformation/test.npy
  raw_data_path: artifacts/data_ingestion/churn/Customer-Churn-Records.csv
  preprocessor_obj_file_path: artifacts/data_transformation/preprocessor.pkl


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.npy
  test_data_path: artifacts/data_transformation/test.npy
  data_path: artifacts/data_transformation/train.csv
  model_path: artifacts/model_trainer/best_model.pkl




model_prediction:
  preprocessor_obj_file_path: artifacts/data_transformation/preprocessor.pkl
  model_path: artifacts/model_trainer/best_model.pkl
